#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout (rgba32f, binding = 0) uniform image2D image;

uniform float time;

vec4 wave(vec2 position, vec2 center, float amplitude, float velocity, float period) {
    float d = distance(position, center) + 0.00001;
    float T = -d * period + time * velocity;
    float value = amplitude * sin(T);
    vec3 gx = vec3(1.0, amplitude * cos(T) * period * (position.x - center.x) / d, 0.0);
    vec3 gy = vec3(0.0, amplitude * cos(T) * period * (position.y - center.y) / d, 1.0);
    vec3 normal = -normalize(cross(gx, gy));
    return vec4(normal, value);
}

void main() {
    ivec2 texel_index = ivec2(gl_GlobalInvocationID.xy);
    ivec2 grid_size = imageSize(image);
    vec2 point = vec2(
        2.0 * texel_index.x / grid_size.x - 1, 
        2.0 * texel_index.y / grid_size.y - 1
    );

    vec4 value = (
        wave(point, vec2(0.23, -0.43), 0.025, 3.0, 8.0) +
        wave(point, vec2(-0.73, -0.53), 0.025, 3.0, 8.0) +
        wave(point, vec2(-1.23, -0.23), 0.025 * 0.5, 3.0, 16.0) +
        wave(point, vec2(0.88, 1.23), 0.025 * 0.5, 3.0, 16.0) +
        wave(point, vec2(0.02, -3.23), 0.025 * 0.5 * 0.5, 3.0, 32.0) +
        wave(point, vec2(0.08, -0.15), 0.025 * 0.5 * 0.5, 3.0, 32.0) +
        wave(point, vec2(0.1, -1.0), 0.025 * 0.5 * 0.5 * 0.5, 3.0, 64.0) +
        wave(point, vec2(2.1, 0.73), 0.025 * 0.5 * 0.5 * 0.5, 3.0, 64.0) +
        wave(point, vec2(0.1, -0.3), 0.025 * 0.5 * 0.5 * 0.5 * 0.5, 3.0, 128.0) +
        wave(point, vec2(2.1, 0.15), 0.025 * 0.5 * 0.5 * 0.5 * 0.5, 3.0, 128.0) +
        wave(point, vec2(-0.6, -0.45), 0.025 * 0.5 * 0.5 * 0.5 * 0.5 * 0.5, 3.0, 256.0) +
        wave(point, vec2(0.79, 0.15), 0.025 * 0.5 * 0.5 * 0.5 * 0.5 * 0.5, 3.0, 256.0)
        
    );

    value.xyz = normalize(value.xyz);
    
    imageStore(image, texel_index, value);
}